
services:
  app:
    container_name: egypt_national_id
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        python app/database_seeds.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop uvloop
      "
    networks:
      - my-network

  postgres:
    image: postgres:17.0
    container_name: national_id_database
    env_file:
      - ./database.env
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d APIUSAGE -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    env_file:
      - ./database.env
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
