from enum import Enum


class ErrorCodeEnum(Enum):
    INVALID_ID = "INVALID_ID"
    PARSING_ERROR = "PARSING_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    SOMETHING_WENT_WRONG = "SOEMTHING_WENT_WRONG"
    TOO_MANY_REQUEST = "TOO_MANY_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"


class SuccessCodeEnum(Enum):
    VALID_ID = "VALID_ID"
