from enum import Enum


class ErrorCodeEnum(Enum):
    INVALID_ID = "INVALID_ID"
    PARSING_ERROR = "PARSING_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SOMETHING_WENT_WRONG = "SOEMTHING_WENT_WRONG"
    TOO_MANY_REQUEST = "TOO_MANY_REQUEST"


class SuccessCodeEnum(Enum):
    VALID_ID = "VALID_ID"
