name: egypt_national_id CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      DATABASE_URL: postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb
      TEST_DATABASE_URL: postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb


    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4


      - name:  Set up Python 3.13.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.7"

      - name:  Install Poetry
        run: pip install poetry==2.1.4

      - name:  Install dependencies
        run: |
          cd national_id_api
          poetry config virtualenvs.create false
          poetry install --with dev --no-root
          poetry add --dev flake8

      - name:  Run Alembic migrations
        run: poetry run alembic upgrade head

      - name:  Seed the database
        run: poetry run python app/database_seeds.py

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with pytest
        run: poetry run pytest
