name: egypt_national_id CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  checks: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      DATABASE_URL: postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb
      TEST_DATABASE_URL: postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb


    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4


      - name:  Set up Python 3.13.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.7"

      - name:  Install Poetry
        run: pip install poetry==2.1.4

      - name:  Install dependencies
        run: |
          cd national_id_api
          poetry config virtualenvs.create false
          poetry install --with dev --no-root
          poetry add --dev autopep8
      - name: Format code with autopep8
        run: |
           cd national_id_api
           poetry run autopep8 --in-place --recursive --max-line-length 500 .

      - name:  Run Alembic migrations
        run: |
          cd national_id_api
          poetry run alembic upgrade head



      # - name: Run tests with pytest
      #   run: |
      #     cd national_id_api
      #     poetry run pytest
      - name: Run tests with coverage
        run: |
          cd national_id_api
          mkdir -p tests/reports
          poetry run pytest tests/ \
            --tb=short \
            --disable-warnings \
            --cov=. \
            --cov-config=.coveragerc \
            --cov-report=xml:tests/reports/coverage.xml \
            --cov-report=term \
            --junitxml=tests/reports/pytest-results.xml | tee tests/reports/pytest-results.txt
        continue-on-error: true

      - name: Publish test results to PR
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: "national_id_api/tests/reports/pytest-results.xml"
      - name: Create test + coverage comment
        run: |
          cd national_id_api
          echo "<!-- test-and-coverage-comment -->" > pr_comment.md
          echo "### 🧪 Test & Coverage Summary" | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY
          echo '```' | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY
          tail -n 20 tests/reports/pytest-results.txt | grep -E "={4,}|PASSED|FAILED|SKIPPED|ERROR|warnings" | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY
          echo "" | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY
          grep -A 1000 "^Name.*Stmts" tests/reports/pytest-results.txt | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY
          echo '```' | tee -a pr_comment.md >> $GITHUB_STEP_SUMMARY

      - name: Find existing bot comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "<!-- test-and-coverage-comment -->"

      - name: Create test & coverage comment
        if: steps.find-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.NATIONAL_ID_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: national_id_api/pr_comment.md
          reactions: rocket

      - name: Update test & coverage comment
        if: steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.NATIONAL_ID_TOKEN }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body-file: national_id_api/pr_comment.md
          reactions: hooray